### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1010]
This is a **change request**

## Problem

New API (Encoder/Decoder/Message/ESM/etc) has some rough edges, need to refine:

- MessageV0/EncoderV0/DecoderV0: User should not need to know what V0 stands for.
- Decoder/Encoder class: the class methods do not really matter to the user. They just need to instantiate the class. Maybe a `createEncoder` function would be enough to export instead of the whole class
- `SymEncoder` `AsymEncoder`, the abbreviation sounds odd. Also got feedback where `ECIES` was expected (from the RFCs)
- exports path: `waitForRemotePeer` is not exported from `@waku/core`. Ideally the user should not need to learn how the export paths/packages and import directly from `@waku/core` by default/in happy path
- All fields of `Message` are optional, so no need to use `Partial`

## Proposed Solutions

- [x] Rename `*V0` to `Encoder`, `Decoder`, `Message`, etc #1049
- [x] Rename `MessageV1` to `Message` (comes from message encryption package so context helps) #1049
- [x] Find better name for `Asym*` and `Sym*` #1049
- [x] provider helper function to create `Decoder`/`Encoder` classes so user does not need to worry about the classes, maybe review if there are some way to `hide` this interface to the user #1049
- [x] Ensure that most things can be imported from `@waku/core` #1049
- [x] Remove usage of `Partial<Message>` where possible #1049
- [x] Do note split early: be sure to think twice before splitting more packages. #1049
- [x] Prefix encoding/decoding/message interfaces with `I` https://github.com/waku-org/js-waku/pull/1049#discussion_r1039113540
- [x] `multiaddrsToPeerInfo` is being implemented twice and exported both times from separate packages. https://github.com/waku-org/js-waku/pull/1067
- [x] Release
- [x]  upgrade examples to latest @waku/core version
- [x] move arguments to options object for createEncoder -> https://github.com/waku-org/js-waku/pull/1146
- [x] https://github.com/waku-org/js-waku/issues/1000 -> https://github.com/waku-org/js-waku/pull/1145

**Comment by danisharora099** [comment]
Extract helper functions into a separate package?

For eg: `multiaddrsToPeerInfo` is being implemented twice and exported both times from separate packages:

![Screenshot 2022-11-24 at 6 33 05 PM](https://user-images.githubusercontent.com/35004822/203791093-c74a11ce-ea4a-442f-b823-a4b04208cf60.png)

**Comment by fryorcraken** [comment]
todos:
- [ ] upgrade examples to latest `@waku/core` version
- [ ] move arguments to `options` object for `createEncoder`

@danisharora099 are you able to take over this issue and tackle the remaining items?

**Comment by fryorcraken** [comment]
- [ ] https://github.com/waku-org/js-waku/issues/1000

**Comment by fryorcraken** [comment]
> From discussion [waku-org/waku-ui#1 (comment)](https://github.com/waku-org/waku-ui/pull/1#discussion_r1109154479)
> 
> > we can have the Light node and relay node implement an interface like that
> 
> ```ts
> interface WakuNode {
>    sender: Sender;
>    receiver: Receiver
> }
> ```

I'd track that in a new issue as it's a big change to improve.

**Comment by fryorcraken** [comment]
Other improvement:

Make `filter.subscribe` and probably `relay.addObserver` too accept a single decoder OR an array of decoder.

**Comment by fryorcraken** [comment]
> Make filter.subscribe and probably relay.addObserver too accept a single decoder OR an array of decoder.

To be covered with https://github.com/waku-org/js-waku/issues/1220
