### ISSUE TITLE
14/WAKU2-MESSAGE: Meta attribute and deterministic hashing

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1208]
This is a **feature  request**

## Problem

https://github.com/vacp2p/rfc/pull/573 introduces two changes to 14/WAKU2-MESSAGE:

1. a new `meta` attribute
2. Deterministic message hashing

See RFC PR for reasoning

## Acceptance Criteria

- [x] `meta` attribute added to protobuf and exposed on https://github.com/waku-org/js-waku/pull/1238
	- [x] encoder API
	- [x] Decoded messages
	- [x] js-noise https://github.com/waku-org/js-noise/pull/36
	- [x] js-rln https://github.com/waku-org/js-rln/pull/61
- [x] Deterministic message hashing logic available (test vectors https://github.com/vacp2p/rfc/pull/577/files) https://github.com/waku-org/js-waku/pull/1233
- [ ] ~Use Deterministic message hashing as a MUID to remove dupes from Relay https://github.com/waku-org/js-waku/pull/1233~ Will be coordinated between clients at a later stage

Cc @LNSD

**Comment by fryorcraken** [comment]
Can talk with @felicio on how they'd expect to use the hash and meta field.

On Waku side usages:
- reduce dupe messages in Store
- avoid relaying dupe messages in relay
- avoid emitting dupe message to user for filter and relay

Note sure on validation logic, need to clarify:
- When receiving a message, the user (ie status web) would check that the meta field contains the hash
- When sending a message a user (ie status web), calculate hash and use to check dupe
- A user may want to use the meta field to check dupe (or should we always use it for dupes if set? or only use the hash for dupes).

**Comment by felicio** [comment]
My notes:

- https://discord.com/channels/864066763682218004/1064649971497971862/threads/1065325922372296714 (discussion)
- https://discord.com/channels/864066763682218004/1064649971497971862/threads/1070650872406753330 (discussion)

**Comment by fryorcraken** [comment]
FYI, first step is to check that gossipsub messages are Waku Messages are not forward them if they aren't: https://github.com/waku-org/js-waku/pull/1227

This we can see the underlying gossipsub API for message verification.

We would probably expose a similar API on Waku Relay but that take Waku Message in input.

And then, expose a similar API for Filter and possibly store so that messages that do not pass the validator are dropped and not emitted/returned.

**Comment by fryorcraken** [comment]
> This we can see the underlying gossipsub API for message verification.

Not "verification" per se, or at least not until a usage of the `meta` field is defined for Status Communities.

> And then, expose a similar API for Filter and possibly store so that messages that do not pass the validator are dropped and not emitted/returned.

Not really any point doing a filtering on `filter` and `store` as the same logic is being implemented in nwaku.
However, could be used in `relay` to filter dupe, the same way it **will** be done in nwaku (hence best to wait for it to be done in nwaku).

**Comment by fryorcraken** [comment]
Note that for Relay/gossipsub. The aim is to use the MUID (`concat(hash,meta)`) to generate the gossipsub message id (previously was `sha256(data)` where `data` is the wire message).

However, I am not sure I understand what would be the gain if the seen window is not changed.

**Comment by fryorcraken** [comment]
@weboko Why did #1237 closed this issue?

**Comment by weboko** [comment]
I believe one of the missing parts is to add support in `js-rln` and `js-noise`. 
@fryorcraken ?

**Comment by fryorcraken** [comment]
> I believe one of the missing parts is to add support in `js-rln` and `js-noise`. @fryorcraken ?

Yes but let's get this https://github.com/waku-org/js-waku/pull/1233 merged first as it uses the new `meta` field.
I have one todo item in the PR and then I want to double check with nwaku devs that my understanding is correct.
