### ISSUE TITLE
Static Sharding

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1310]
**Planned start date**:
**Due date**: 15 Oct 2023

# Summary

Implement Static Sharding as specified in https://rfc.vac.dev/spec/51/#static-sharding

# Acceptance Criteria

As an app dev, I can...

- [x] specify the static shard I am using so that my node connects to nodes serving said shard
- [x] use filter for a given static shard
- [x] use lightpush for a given static shard
- [x] use store for a given static shard
- [x] use relay for a given static shard

## Tasks

Taking into account https://github.com/waku-org/js-waku/issues/1430#issuecomment-1655066881, where we assume that shards will **not** change mid-run; we can update the sequence diagram as:

```mermaid
sequenceDiagram
    participant Alice
    participant js-waku
    participant connection manager

    Alice->>js-waku: start (pass [`shard1`, `shard2`])
    js-waku->>connection manager: discovers & attempts connections to relevant peers
    Alice->>js-waku: send a subscription request that includes a pubsubtopic based on IDecoder
    js-waku->>js-waku: if the new pubsubtopic is different from initialisation, throw error
    js-waku->>js-waku: if the new pubsubtopic is one of the ones from initialisation, proceed
    js-waku->>connection manager: open a stream with one of the connected peers from the relevant shard
    js-waku->>Alice: return the subscription object 
```

this definitely narrows our scope of work (v1) but we can design our system as above discussed where we think of it being potentially scaled up to being used for run-time changes as well (v2?)

-----
### Create
- [x] take in `pubsubTopics` during the creation of node: https://github.com/waku-org/js-waku/pull/1586
   - eg: `const node = createRelayNode({ cluster: M, shards: [N, O] });`

### Discovery 
- [x] when ENR is decoded within discovery classes, find its `rs`/`rsv` and add that information in `PeerStore` for easier access https://github.com/waku-org/js-waku/pull/1626

### [ConnectionManager](https://github.com/waku-org/js-waku/issues/1506) 
- [x] before peers are attempted to dial within the Manager, check if the peer corresponds to a relevant shard by reading its `rs`/`rsv` value & then dial them accordingly https://github.com/waku-org/js-waku/pull/1626

### Protocols
- [x] within individual protocols, when a request is sent, ensure that the `pubsubTopic` for that request is for a shard that the js-waku node was setup with during initialisation: https://github.com/waku-org/js-waku/pull/1586
   -  else, we throw an error

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by fryorcraken** [comment]
> some learnings: js-waku being a client and not actually participating in discv5 discovery process, the implementation would be mostly limited to filtering out the right nodes from discovery protocols; in terms of peer exchange, the goal is to connect only with peers from the PX response that share the same pubsub topic or shard that the relay protocol is subscribed to, while discarding other peers received in the response
> 
> cc @fryorcraken keen to know your perspective on the above

that and we also need to implement the API to enable static and naming sharding on filter, light push, store and relay. Which is the discussion I saw on Twitter.

**Comment by fryorcraken** [comment]
Note this is needed for the "community preview" web portal of Status. Cc @danisharora099 @chair28980 @john-44 @prichodko @felicio

**Comment by John-44** [comment]
> Note this is needed for the "community preview" web portal of Status. Cc @danisharora099 @chair28980 @John-44 @prichodko @felicio

and User Preview web pages + Channel Preview web pages

**Comment by fryorcraken** [comment]
Looks good. Would be good to have a review from @waku-org/go-waku-developers and @waku-org/nwaku-developers if they see any issue from their experience/implementaiton.

Agreed that for static sharding, we can assume that the static shard does not change after a start to support the Community Preview portal and Community Channel web pages for Status. Cc @felicio @prichodko 

Do note that with auto-sharding, shards can change mid run (but out of scope for this issue).

**Comment by danisharora099** [comment]
Closing considering #1684 is done
