### ISSUE TITLE
[Epic] Developer Experience (2023)

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1453]
**Planned start date**:
**Due date**:

# Summary

Tracks the work done on js-waku to improve developer experience.
Items may come from:
- feedback from users
- feedback from documentation writing activities

# Acceptance Criteria

This is a yearly milestone as such report and feedback may happen as long as the library is used.
This includes all js-waku related libraries.

Bug reports should only be tracked here if not related to a 2023 development.

## Tasks

- [ ] #1424
- [ ] #1457
- [x] https://github.com/waku-org/js-waku/issues/1411
- [x] https://github.com/waku-org/js-waku/pull/1466
- [ ] https://github.com/waku-org/js-waku/issues/1465
- [x] https://github.com/waku-org/js-waku/pull/1517 
- [x] https://github.com/waku-org/js-waku/issues/1496
- [x] https://github.com/waku-org/js-waku/issues/1497
- [ ] https://github.com/waku-org/js-waku/issues/1548
- [ ] https://github.com/waku-org/js-waku/issues/1547

# RAID (Risks, Assumptions, Issues and Dependencies)

- This cannot happen if there is no usage of the API
- Some issues may come from dependencies (other libraries)

**Comment by weboko** [comment]
Weekly update:
_achieved_: non blocking pipeline step (https://github.com/waku-org/js-waku/issues/1411)

**Comment by weboko** [comment]
**Weekly update**:
- achieved: added retry for failing CI testing steps

**Comment by weboko** [comment]
**Weekly update**:
- _achieved_: investigation of `go-waku` interop test that is failing - ongoing, fixing next release
- _next_: root cause `go-waku` interop test failure

**Comment by fryorcraken** [comment]
As discussed, this issue was open as a tool to track updates.
We moved away from this process. Instead, we just need to ensure than any dev ex issue with worked on is properly labelled.
