### ISSUE TITLE
[Epic] Maintenance

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1455]
# Summary

Maintenance items that do not directly fit under any other milestones, yet need to be done to avoid problems.
Typically:
- dependencies update (so that we do not wait to _need_ the upgrade to do it)
- bugs that do not fit under #1453 or for milestones that have been shipped _a while back_.
- Releasing

## Tasks

- [x] https://github.com/waku-org/js-waku/pull/1451
- [x] https://github.com/waku-org/js-waku/pull/1462
- [x] https://github.com/waku-org/js-waku/pull/1461
- [x] https://github.com/waku-org/js-waku/pull/1476
- [x] https://github.com/waku-org/js-waku/pull/1471
- [x] https://github.com/waku-org/js-waku/pull/1475
- [x] https://github.com/waku-org/js-waku/pull/1479
- [x] https://github.com/waku-org/waku-ui/pull/23
- [x] https://github.com/waku-org/js-waku/pull/1481
- [x] https://github.com/waku-org/js-waku/pull/1480
- [ ] https://github.com/waku-org/js-waku/pull/1486
- [x] https://github.com/waku-org/js-waku/pull/1488
- [x] https://github.com/waku-org/js-waku/pull/1456
- [x] #1495 
- [x] https://github.com/waku-org/js-waku/pull/1499
- [x] https://github.com/waku-org/js-waku/pull/1525
- [ ] https://github.com/waku-org/js-waku/pull/1528
- [ ] https://github.com/waku-org/js-waku/issues/1562
- [ ] https://github.com/waku-org/js-waku/issues/1565
- [x] https://github.com/waku-org/js-waku/issues/1553
- [ ] https://github.com/waku-org/js-waku/issues/1508
- [ ] https://github.com/waku-org/js-waku/issues/1564
- [x] https://github.com/waku-org/js-waku/issues/1563
- [ ] https://github.com/waku-org/js-waku/pull/1583

# RAID (Risks, Assumptions, Issues and Dependencies)

- Tackling dependencies upgrade on regular basis avoid big block of time spent when the dep upgrade blocks another milestone
- This may become a dumping ground, let's thrive to not let this happen.

**Comment by weboko** [comment]
Weekly update:
_achieved_: examples and `@waku/react` deps update
_next_: leftover examples upgrade, maybe dependabot PRs

**Comment by weboko** [comment]
**Weekly update**:
- _achieved_: @chainsafe/libp2p-gossipsub is updated

**Comment by weboko** [comment]
**Weekly update**:
- _achieved_: updated typescript + plugins to major versions, waiting to merge for release

**Comment by weboko** [comment]
**Weekly update**:
- _achieved_: added logs, investigated issues reported
- _next_: approach reported issues, add preventative measures

**Comment by fryorcraken** [comment]
Maintenance work does not need to be tracked with an Epic. Ref: https://github.com/waku-org/pm/pull/91
