### ISSUE TITLE
[Epic] Speed optimizations

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#1521]
**Planned start date**:
**Due date**:

# Summary

Tracks the work done on `js-waku` to improve **speed**, **latency**, and other critical parameters to the fluency of `js-waku`.
Items may come from:
- core contributor's research
- feedback from consumers

# Acceptance Criteria

This is a yearly milestone as such report and feedback may happen as long as the library is used.

Bug reports should only be tracked here if not related to a 2023 development.

## Tasks

- [ ] Investigate re-usability of streams ([comment](https://github.com/waku-org/js-waku/pull/1516/files#r1312128559));
- [ ] Make full use of `Promise.all` when possible;
- [ ] Test suit to measure latency of critical parts: `lightPush.send` etc;

# RAID (Risks, Assumptions, Issues and Dependencies)

- This cannot happen if there is no usage of the API
- Some issues may come from contributors, consumers, partner teams

**Comment by fryorcraken** [comment]
> Investigate re-usability of streams ([comment](https://github.com/waku-org/js-waku/pull/1516/files#r1312128559));

We confirmed that libp2p's best practice is to **not* re-use a stream for req-res protocols.

The first item is already tracked in https://github.com/waku-org/js-waku/issues/1465 so not sure to see a need to double track.
