### ISSUE TITLE
feat: configure playwright to test other examples based on env var

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#1597]
This is a **feature request**

## Problem

In https://github.com/waku-org/js-waku/issues/1418 Playwright was configured to extract and test only one example which is `web-chat`. 
We have other examples that are worth shallow testing in the browser - a reason for that is to check the compatibility of `js-waku` with different Fron-End frameworks. 

## Proposed Solutions

By passing env variables we can re-configure Pralywright CI to test other examples as well. 
A new set of tests can be written for other examples and should be run dependently on an example under testing. 

## Subtasks

- [ ] Configure Playwright CI to be an action for re-usability reasons;
- [ ] Make bootstrap scripts example agnostic;
- [ ] Write new set of test for other examples if needed;
- [ ] Add CI stages to test different examples;

## Notes

Refs: https://github.com/waku-org/pm/issues/90

**Comment by weboko** [comment]
Not needed, will be covered in https://github.com/waku-org/js-waku/issues/2217
