### ISSUE TITLE
[Epic: js-waku] Operator mission dogfooding app

### ISSUE THREAD

**Issue by chair28980** [waku-org/js-waku#2151]
## Tasks

- [x] https://github.com/waku-org/lab.waku.org/issues/69
- [x] Fix lab.waku.org repository (@weboko)
- [x] Follow up on which fleet to use (@weboko)
- [ ] Update UX - make experience passive and improve FE (@hackyguru for FE update)
- [x] Provide support by telemetry service: db support. https://github.com/status-im/telemetry/pull/20 (@adklempner)
- [ ] *low priority*: Investigate possibility of using similar approach in js-waku - https://github.com/waku-org/storenode-messages-counter
