### ISSUE TITLE
feat: refine unit test setup and add utils

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#2165]
## Problem

Presently our setup can be more efficient and a lot of config duplications can be removed.

## Solution

We should revisit our `karma`, `chai` setup. 
Organize setup scripts for them and share between packages. 

## TODO

- [ ] move `chai`/`mocha` dependencies to root `package.json`;
- [ ] add root configuration for them with needed plugins such as `chai-as-promised`;
- [ ] unit tests have shared code that generates mocked objects for `libp2p` primitives - we need to decouple it to a new package `@waku/test-utils` (example of such utils - here);
