### ISSUE TITLE
[Subtask] Add and refine telemetry

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#2179]
### Description 

Add and refine telemetry to user facing apps and make sure privacy policy is enforced. 

This task includes:
- [ ] Create Telemetry dashboards on Superset
- [x] Ensure presence of Privacy policy on an app under observation 
- [x] Add telemetry tracking points in apps under observation

**Comment by weboko** [comment]
Descoped separate dashboards as volume of data was low and we can use direct sql queries.
