### ISSUE TITLE
Cover Several Environments As Part of Testing

### ISSUE THREAD

**Issue by D4nte** [waku-org/js-waku#52]
**Planned start date**:
**Due date**:

# Summary

js-waku library is meant for browser usage.
Most of the testing is currently done via NodeJS, which is not ideal especially that cryptographic functions uses the Web Crypto API or NodeJS's crypto modules or bindings. Meaning testing in NodeJS does not mean it would work in the Browser.

https://github.com/status-im/js-waku/pull/230 laid some basis on how to get browser testing as part of the CI. However, it is not complete:

1. No Firefox run (only chrome)
1. No test done against nim-waku for js-waku in the browser

# Acceptance Criteria

- [x] js-waku tests run against both Chrome and Firefox web engines
- [x] js-waku test include bundling and running a simple apps written in several framework (TBD, at least React and Vite)

# Tasks

- [x] Add `FirefoxHeadless` to the browser list and make it work https://github.com/waku-org/js-waku/pull/1598
- [ ] Orchestrate the spin up of a nim-waku instance #887 (most likely needed to achieve the above)
- [x] Bundlers support? https://github.com/waku-org/js-waku/issues/1418

Note: [aegir](https://ipfs.github.io/aegir/) uses Karma for browser tests so it should be possible to test it. It could make orchestration easier thanks to the `before` and `after` hooks.

# RAID (Risks, Assumptions, Issues and Dependencies)

- Need to avoid scope creep for this issue. In terms of bundler testing, the most demanded framework so far are React and Svelte
- It seems that migration to Jest may be needed to more easily achieve this task

**Comment by littlealex003** [comment]
You want to deploy the code, fire up a browser and connect to it with something like Selenium, to replicate a real deployment, correct?

**Comment by D4nte** [comment]
I do not have much knowledge about testing JS code against a browser. What are the options?

Yes, the idea is to ensure that the library is tested in an environment closest to real deployment.

Something similar to what [js-libp2p does](https://github.com/libp2p/js-libp2p/blob/5282708263df4894e222445e501686b27d00c16e/package.json#L42) should be good enough.

**Comment by littlealex003** [comment]
I will look at the js-libp2p; I mean if we want to we can do a full automated deployment, launch browsers with automated control, and run tests against the actual deployed application, on as many different OS / Browser combinations as we like. It really depends how many platforms we want to support and thorough we want to be about testing the JavaScript on different platforms and browsers.

The tests I saw before looked like they were using mocked objects, I'm not sure what automated tests there are but I'll look more.

**Comment by littlealex003** [comment]
It looks like js-libp2p is using https://ipfs.github.io/aegir/ I'm not familiar with it; it has a "browser" test mode, though it's not entirely clear what that is doing. We could implement this same library

**Comment by D4nte** [comment]
Hum, I am enjoy the integration of Webstorm (my IDE) with mocha/chai. Not really keen to move to another test framework that does not integrate well (I moved away from ava for this reason exactly).

Isn't selenium about testing UI component and simulating user actions? We don't really do that as js-waku does not have an UI element.

**Comment by littlealex003** [comment]
Yeah Mocha/Chai is pretty much the standard I find, so good to stay with
that, I was just looking at what the other project was doing for "browser"
testing based on their package.json and it seems that this tool provides to
solution. What exactly it is doing, and what exactly "browser" testing
means in that environment or in general seems unclear.

To me browser testing is deploying a full end to end application with a Web
UI component and testing that UI in the browser, as that is how end users
will end up using it, so it may be a matter of semantics; I'm not exactly
sure how anything else is actually testing the browser though.

We could certainly deploy our code and load the example App in a browser
and make sure it works as a way of testing to make sure the JavaScript
works in actual browsers on actual OSes, that is what I thought you had in
mind; I'm more used to working with independent CI/CD systems like Jenkins
or others than what is integrated into GitHub but I think we could use
Docker to build a real deployment scenario and they offer both Windows and
Mac OS resources as well (though I'm not sure how the monetization model
looks).

I will look through more of the tests, the other tasks were a bit more
clear so I was holding off on this until I got more info from you.

**Comment by weboko** [comment]
*Weekly update*:
- _achieved_: browser testing is redone and opening for review
- _next_: integrate with release process - rather quick follow up, revisit current epic

**Comment by weboko** [comment]
**Weekly update**:
- _achieved_: got reviews on playwrights tests
- _next_: maybe add bounty, check Karma testing

**Comment by weboko** [comment]
**Weekly update**:
- _achieved_: improved karma testing, added testing in browser

**Comment by weboko** [comment]
Since https://github.com/waku-org/js-waku/issues/887 is not urgent delaying the ticket.

**Comment by fryorcraken** [comment]
@weboko I think we can close thsi issue as we now test in Firefox and webkit. #887 can be a ticket on its own.

**Comment by weboko** [comment]
@fryorcraken agree, closing
